name: Browser Desktop (noVNC)
on: workflow_dispatch

jobs:
  desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Install desktop + VNC + noVNC
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-terminal x11vnc xvfb websockify curl git
          mkdir -p ~/.vnc
          # set VNC password
          x11vnc -storepasswd "changeme123" ~/.vnc/passwd
          # get noVNC
          git clone https://github.com/novnc/noVNC.git ~/noVNC
          git clone https://github.com/novnc/websockify ~/noVNC/utils/websockify

      - name: Start X and desktop
        run: |
          Xvfb :99 -screen 0 1280x800x24 &
          export DISPLAY=:99
          startxfce4 &

      - name: Start VNC and noVNC
        run: |
          export DISPLAY=:99
          x11vnc -rfbauth ~/.vnc/passwd -display :99 -forever -shared -rfbport 5901 -nopw -quiet &
          ~/noVNC/utils/novnc_proxy --vnc localhost:5901 --listen 6080 &

      - name: Expose with Cloudflare tunnel
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          ./cloudflared tunnel --url http://localhost:6080 --no-autoupdate 2>&1 | tee tunnel.log &
          sleep 8
          echo "----------------------------------------------------"
          echo "Your noVNC URL(s):"
          grep -oE 'https://[-a-z0-9]+\.trycloudflare\.com' tunnel.log | sort -u
          echo "----------------------------------------------------"
          echo "VNC password: vnc@4321"
          echo "----------------------------------------------------"

      - name: Keep alive
        run: |
          while true; do echo "alive $(date)"; sleep 60; done
