name: Ubuntu - RustDesk Runner

on:
  workflow_dispatch:

jobs:
  build:
    name: Start RustDesk on ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 350   # GitHub max on Ubuntu is 360 mins

    steps:
      - name: Generate RustDesk credentials
        id: creds
        run: |
          set -e
          ID=$((RANDOM%900000+100000))
          PASS=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 10)
          echo "RUSTDESK_ID=$ID"      | tee -a $GITHUB_ENV
          echo "RUSTDESK_PASSWORD=$PASS" | tee -a $GITHUB_ENV
          echo "✅ Credentials generated: ID=$ID  PASS=$PASS"

      - name: Prepare system (deps)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xvfb libgtk-3-0 libxcb-shape0 libxcb-xfixes0 libxkbcommon0 libx11-xcb1 libxcb1 libxi6 libxrandr2 libxcb-render0 libxcb-shm0

      # If RustDesk version changes, just update the two variables below.
      - name: Download RustDesk .deb
        env:
          RUSTDESK_VERSION: "1.2.3"          # <-- change if needed
          RUSTDESK_DEB: "rustdesk-1.2.3-x86_64.deb"
        run: |
          set -e
          URL="https://github.com/rustdesk/rustdesk/releases/download/${RUSTDESK_VERSION}/${RUSTDESK_DEB}"
          echo "Downloading $URL"
          wget -q "$URL" -O rustdesk.deb

      - name: Install RustDesk
        run: |
          sudo dpkg -i rustdesk.deb || sudo apt-get -f install -y
          rustdesk --version || true
          echo "✅ RustDesk installed"

      - name: Seed password & minimal config
        run: |
          mkdir -p ~/.config/rustdesk
          cat > ~/.config/rustdesk/RustDesk.toml <<'EOF'
          [options]
          # Minimal headless-friendly options; adjust if you run your own hbbs/hbbr.
          # enable_audio = false
          # enable_file_transfer = false
          EOF
          # Store the password so RustDesk can auto-accept with it if needed
          echo -n "${RUSTDESK_PASSWORD}" > ~/.config/rustdesk/password
          chmod 600 ~/.config/rustdesk/password

      - name: Start RustDesk (headless)
        run: |
          # Launch under xvfb so GUI requirements are satisfied
          nohup xvfb-run -a rustdesk >/tmp/rustdesk.log 2>&1 &
          sleep 5
          echo "=========================================="
          echo "🚀 RUSTDESK RUNNER READY"
          echo "ID: ${RUSTDESK_ID}"
          echo "Password: ${RUSTDESK_PASSWORD}"
          echo "=========================================="
          echo "Logs tail (first 50 lines below):"
          sleep 2
          head -n 50 /tmp/rustdesk.log || true

      - name: Keep alive
        run: |
          echo "🔄 Keeping the runner alive for remote access..."
          for i in $(seq 1 20000); do
            echo "✅ Alive - $(date)"
            sleep 60
          done
